#
DEFINES = RASPPI #NDEBUG
#
EXTRA_INCLUDES = ../lib-properties/include ../lib-remoteconfig/include ../lib-spiflashstore/include ../lib-artnet/include ../lib-artnet4/include ../lib-e131/include ../lib-ledblink/include ../lib-lightset/include ../lib-network/include ../lib-bob/include ../lib-i2c/include ../lib-tftpdeamon/include
#
include ../linux-template/lib/Rules.mk
