#
PLATFORM = ORANGE_PI
#
DEFINES = ARTNET_NODE PIXEL DISPLAY_UDF DISPLAY_NEXTION RDMNET_LLRP_ONLY NDEBUG
#
LIBS = nextion
#
SRCDIR = firmware lib

include ../h3-firmware-template/Rules.mk

prerequisites:

